### ISSUE TITLE
Error when breaking cycles

### ISSUE THREAD

**Issue by leio10** [amcfague/linesman#31]
I get an "Index out of range" error in linesman/middleware.py, line 441.

It is the breaking cycles code. You call the "simple_cycles" function from networkx, and it returns a list of lists with circuits of nodes. These lists could have just one element, and so the next code produces the error.
   
     u, v = cycle[0], cycle[1]

I've changed it to

    u, v = cycle[0], cycle[-1]

and it works, but I don't know if it's semantically right.

thanks,
Leo

**Comment by amcfague** [comment]
Closing as duplicate.
