### ISSUE TITLE
Permanently delete filtered sessions button does not always from the right request to the backend.

### ISSUE THREAD

**Issue by ChrisWheat** [amcfague/linesman#34]
Hello,

I have found linesman to be a very useful profiling tool for my wgsi app. I just want to point out a really minor issue with the UI. If a forward slash is not added to the end of the root name of the path the "permanently delete filtered session" button will not form the correct delete request. For example, when viewing the page in the browser with the url  (http://host/__profiler__) the resulting delete url seen by the backend is (http://host/__profiler__delete) and nothing will be deleted from the database. If the page is viewed with the url (http://host/__profiler__/), everything works fine. 

Keep up the awesome work!

Thanks,
Chris

**Comment by amcfague** [comment]
Hi Chris.  Looks like this only impacts the bulk delete.  I've gone ahead and fixed this.  Thanks for letting me know!
