### ISSUE TITLE
Conflict with: filter-with = gzip

### ISSUE THREAD

**Issue by mrkafk** [amcfague/linesman#36]
I have lots of HTML generated in internal web app (Pyramid), so I'm using `filter-with = gzip`. It seems that it conflicts with `filter-with = linesman`. 

When I comment `filter-with = gzip` out,  ".../\_\_profiler\_\_" page opens fine. Otherwise I get 404.

I'm using pserve (waitress) like so:

    pserve development.ini --reload

**Comment by amcfague** [comment]
Are you specifying them both at the same configuration block?  It looks like you need to either chain them together, or use the `pipeline` option: http://pythonpaste.org/deploy/#filter-composition

**Comment by mrkafk** [comment]
Yes, I used them separately (did not pipeline). I will try if that works. Thanks!
